version: '3.5'

services:
  nano:
    container_name: bot
    build: .
    command: python nano/client.py
    volumes:
      - ./nano:/app/nano
    ports:
      - "8000:8000"
    environment:
      NANO_CONFIG: /var/run/secrets/nano_config
    secrets:
      - nano_config

secrets:
  nano_config:
    file: ./config.yml
